name: Compile Compact Styles
on:
  push:
    branches:
      - compact
jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Compiling
        run: |
          npm i
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUBACTIONSTOKEN }}
          publish_dir: ./build
